### ISSUE TITLE
getting user logout after payment completed 

### ISSUE THREAD

**Issue by shakhawatfci** [sslcommerz/SSLCommerz-PHP#3]
i am using ssl commerz SDK the one which is defined for php in official documentation everything is fine payment gateway working fine but it's login me out of the application ..

does it destroy the session ?

i am using it on Laravel 7 and for user authentication using Laravel Auth

**Comment by rkbi** [comment]
This is for RAW PHP. There is another example for laravel at - https://github.com/sslcommerz/Integration_in_Laravel-5.6-with-IPN. Despite the name, works fine with laravel 7.

**Comment by shakhawatfci** [comment]
laravel also php 😕 anyway the laravel docs not much clear . I did manage
with old one

Thanks

**Comment by kashohel** [comment]
This package is compatible with Laravel 7 but the same_site setting is changed in default Laravel installation, make sure you change same_site to null in config/session.php or callback won't include cookies and you will be logged out when a payment is completed. So inside your config/session.php update

```
return [
  ...
  ...
  'same_site' => null,
  ...
  ...
];
```
